### ISSUE TITLE
some calls don't work after updating to V3+

### ISSUE THREAD

**Issue by marvinm2** [bridgedb/docker#23]
When testing the v3.0.13 version, some calls work (such as the properties call), but some don't and return an internal server error, including:
- ​/{organism}​/xrefs​/{systemCode}​/{identifier}
- /{organism}/xrefsBatch/{systemCode}
- /{organism}/search/{query}
- /{organism}/attributeSearch/{query}
- [​/{organism}​/attributes​/{systemCode}​/{identifier}

Interestingly, the call /{organism}/xrefsBatch does work for ID mapping

**Comment by marvinm2** [comment]
These functions work normally on the live webservice (which is version 3.0.2)

I also tested a Docker image of BridgeDb version 3.0.2

**Comment by marvinm2** [comment]
Error messages in logs:
```
Apr 13, 2022 9:36:57 AM org.restlet.engine.application.StatusFilter doHandle
WARNING: Exception or error caught in status service
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.restlet.routing.Route.extractAttributes(Route.java:273)
	at org.restlet.routing.Route.beforeHandle(Route.java:249)
	at org.restlet.routing.Filter.handle(Filter.java:204)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:391)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
	at org.restlet.Component.handle(Component.java:391)
	at org.restlet.Server.handle(Server.java:491)
	at org.restlet.engine.http.connector.BaseServerHelper.handle(BaseServerHelper.java:161)
	at org.restlet.engine.http.connector.BaseServerHelper.handleInbound(BaseServerHelper.java:170)
	at org.restlet.engine.http.connector.BaseHelper.handleNextInbound(BaseHelper.java:421)
	at org.restlet.engine.http.connector.Connection.readMessages(Connection.java:698)
	at org.restlet.engine.http.connector.Controller$2.run(Controller.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Apr 13, 2022 9:36:57 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2022-04-13	09:36:57	127.0.0.1	-	-	8183	GET	/Human/xrefs/L/1234	-	500	486	0	2	http://127.0.0.1:8183	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36	-
Apr 13, 2022 9:36:57 AM org.restlet.resource.UniformResource doCatch
WARNING: Exception or error caught in resource
java.lang.IllegalArgumentException: Unknown organism: favicon.ico<p><font size='+1'><i>Double check the spelling. We are expecting an entry like: Human</i></font></p>
	at org.bridgedb.server.IDMapperResource.initIDMappers(IDMapperResource.java:77)
	at org.bridgedb.server.IDMapperResource.doInit(IDMapperResource.java:55)
	at org.restlet.resource.UniformResource.init(UniformResource.java:579)
	at org.restlet.resource.Finder.handle(Finder.java:510)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:391)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
	at org.restlet.Component.handle(Component.java:391)
	at org.restlet.Server.handle(Server.java:491)
	at org.restlet.engine.http.connector.BaseServerHelper.handle(BaseServerHelper.java:161)
	at org.restlet.engine.http.connector.BaseServerHelper.handleInbound(BaseServerHelper.java:170)
	at org.restlet.engine.http.connector.BaseHelper.handleNextInbound(BaseHelper.java:421)
	at org.restlet.engine.http.connector.Connection.readMessages(Connection.java:698)
	at org.restlet.engine.http.connector.Controller$2.run(Controller.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Apr 13, 2022 9:36:57 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2022-04-13	09:36:57	127.0.0.1	-	-	8183	GET	/favicon.ico	-	500	486	0	2	http://127.0.0.1:8183	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36	http://localhost:8080/Human/xrefs/L/1234
```

**Comment by marvinm2** [comment]
Tested the latest version (3.0.22-2.1.4) locally. All calls work.
