### ISSUE TITLE
xref not working

### ISSUE THREAD

**Issue by marvinm2** [bridgedb/docker#25]
```
May 31, 2022 2:24:16 PM org.restlet.engine.application.StatusFilter doHandle
WARNING: Exception or error caught in status service
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.restlet.routing.Route.extractAttributes(Route.java:273)
	at org.restlet.routing.Route.beforeHandle(Route.java:249)
	at org.restlet.routing.Filter.handle(Filter.java:204)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:391)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:500)
	at org.restlet.routing.Router.handle(Router.java:740)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114)
	at org.restlet.Component.handle(Component.java:391)
	at org.restlet.Server.handle(Server.java:491)
	at org.restlet.engine.http.connector.BaseServerHelper.handle(BaseServerHelper.java:161)
	at org.restlet.engine.http.connector.BaseServerHelper.handleInbound(BaseServerHelper.java:170)
	at org.restlet.engine.http.connector.BaseHelper.handleNextInbound(BaseHelper.java:421)
	at org.restlet.engine.http.connector.Connection.readMessages(Connection.java:698)
	at org.restlet.engine.http.connector.Controller$2.run(Controller.java:98)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

May 31, 2022 2:24:16 PM org.restlet.engine.log.LogFilter afterHandle
INFO: 2022-05-31	14:24:16	127.0.0.1	-	-	8183	GET	/Human/xrefs/L/1234	-	500	486	0	7	http://127.0.0.1:8183	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36	http://localhost:8080/swagger/
```

**Comment by marvinm2** [comment]
With the latest versions, this call works normally
